version: '3.3'

services:
  pictshare:
    image: hascheksolutions/pictshare:latest
    ports:
      - "804:80"
    volumes:
      - ./pictshare:/usr/share/nginx/html/data
      - ./config.inc.php:/usr/share/nginx/html/inc/config.inc.php
      - ./pictshare.sh:/pictshare.sh
volumes:
  pictshare:
